spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        multiTenancy: DATABASE
        multi_tenant_connection_provider: com.example.notificationservice.config.TenantConnectionProvider
        multi_tenant_identifier_resolver: com.example.notificationservice.config.TenantIdentifierResolver
  sql:
    init:
      mode: always
      schema-locations: classpath:db/public-schema.sql
      continue-on-error: true

server:
  port: 8080

twilio:
  account:
    sid: ${TWILIO_ACCOUNT_SID:your_account_sid}
  auth:
    token: ${TWILIO_AUTH_TOKEN:your_auth_token}
  phone:
    number: ${TWILIO_PHONE_NUMBER:your_phone_number} 